# Generated by Django 4.0.5 on 2022-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='user_profile',
            field=models.ManyToManyField(to='app.userprofile'),
        ),
    ]
