# Generated by Django 4.0.5 on 2022-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feature_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='released_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
