# Generated by Django 3.2.4 on 2022-06-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_version_released_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
