# Generated by Django 3.2.4 on 2022-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
