# Generated by Django 4.0.5 on 2022-06-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_version_released'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Element',
        ),
    ]
