# Generated by Django 4.0.5 on 2022-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_feature_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='feature_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
