# Generated by Django 4.0.5 on 2022-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_element_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='feature_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
