# Generated by Django 4.0.5 on 2022-06-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_element_feature_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ManyToManyField(to='app.userprofile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.version')),
            ],
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
