# Generated by Django 4.0.5 on 2022-06-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_task_delete_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Pending verification', 'Pending verification'), ('Closed', 'Closed')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_end',
            field=models.CharField(choices=[('Front end', 'Front end'), ('Back end', 'Back end'), ('Full stack', 'Full stack')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Small adjustment', 'Small adjustment'), ('Architecture tuning', 'Architecture tuning'), ('New feature', 'New feature')], max_length=50),
        ),
    ]
