# Generated by Django 4.0.5 on 2022-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_task_status_task_task_end_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Pending verification', 'Pending verification'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
